/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sampleproject;

import org.junit.jupiter.api.Test;

import TimerApp.TimerApp;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        TimerApp classUnderTest = new TimerApp();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
