/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TimerApp;

public class TimerApp {
    
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new TimerApp().getGreeting());
    }
}
